CONFIG_ZMK_KEYBOARD_NAME="Sofle"
CONFIG_ZMK_DISPLAY_WORK_QUEUE_DEDICATED=y

# Uncomment these two line to add support for encoders to your firmware
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Uncomment the following line to enable the Nice View Display
CONFIG_ZMK_DISPLAY=n

# BLE configs
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y  # set transmission power to max
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y
CONFIG_BT_CTLR_PHY_2M=n
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y

# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Enable mouse keys
CONFIG_ZMK_MOUSE=y


# Uncomment this line below to add rgb underglow / backlight support
CONFIG_ZMK_RGB_UNDERGLOW=y

# Uncomment the line below to disable external power toggling by the underglow.
# By default toggling the underglow on and off also toggles external power
# on and off. This also causes the display to turn off.
CONFIG_ZMK_RGB_UNDERGLOW_EXT_POWER=n
