file_format: "1"
id: swept2
name: Swept
type: shield
url: https://github.com/thuatdt137/zmk-config-hillsideview
requires:
  - pro_micro
exposes:
  - nice_view_header
features:
  - keys
  - display
  - underglow
siblings:
  - swept_left
  - swept_right
