file_format: "1"
id: sofle1
name: Sofle
type: shield
url: https://github.com/thuatdt137/zmk-configs
requires:
  - pro_micro
exposes:
  - nice_view_header
features:
  - keys
  - display
  - underglow
siblings:
  - sofle_left
  - sofle_right
